# Generated by Django 4.0.2 on 2022-03-19 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Sản phẩm', 'verbose_name_plural': 'Sản phẩm'},
        ),
        migrations.AlterModelOptions(
            name='productgallery',
            options={'verbose_name': 'Hình ảnh sản phẩm', 'verbose_name_plural': 'Hình ảnh sản phẩm'},
        ),
        migrations.AlterModelOptions(
            name='variation',
            options={'verbose_name': 'Thuộc tính sản phẩm', 'verbose_name_plural': 'Thuộc tính sản phẩm'},
        ),
    ]
