# Generated by Django 4.0.2 on 2022-02-21 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_profile_options_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_images',
            field=models.ImageField(upload_to='products'),
        ),
        migrations.AlterField(
            model_name='productgallery',
            name='image',
            field=models.ImageField(max_length=255, upload_to='products'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatar'),
        ),
    ]
