# Generated by Django 4.0.2 on 2022-02-22 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_profile_options_alter_profile_bio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='url_mail',
            new_name='mail',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='url_tel',
            new_name='tel',
        ),
    ]
