# Generated by Django 4.0.2 on 2022-02-22 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_rename_url_mail_profile_mail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mail',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tel',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
